### ISSUE TITLE
Rename tablet view e.g. to "commandpanel"

### ISSUE THREAD

**Issue by jpawlowski** [Hoanoho/Hoanoho#70]
We should rename the /tablet view to something like "command panel" as the default view is actually kind of a hybrid view for desktop and rich tablets and it seems to confuse users seeing there is a dedicated tablet view while this is for a special use case and not for their general use on iPads.

**Comment by poffel1976** [comment]
What about "controlCenter"? Or should we keep all in lower letters? Otherwise this should not really be a big deal/issue cause it's just renaming 3 or 4 places in the sourcecode.

**Comment by jpawlowski** [comment]
There is a bit more to change also in the other repositories but yes, it's not a big deal at all.
Just wanted to get some input about any alternative name. Control Center might not be very accurate as all the other views are for controlling purposes as well. The difference is more this is a specific view to be used at wall mounted devices for which "panel" would be a better term. Maybe Control Panel is what I was looking for ;)

Reg upper/lower case: URI items all are lower case as they are case-insensitive anyway.
